AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: >-
  Lambda functions template to run locally with SAM-CLI and ready deploy on AWS

Resources:
  CheckLogPresenceFunction:
    Type: AWS::Serverless::Function
    package:
      individually: true
      exclude:
        - aws-java-sdk
    Properties:
      FunctionName: CheckLogPresence
      Description: Function to check the presence of the log given a timestamp
      Runtime: java8
      Handler: proxy.ApiGatewayProxyHandler
      CodeUri: target/scala-3.0.2/acappe2_hw3.jar
      MemorySize: 512
      Timeout: 50
      Environment:
        Variables:
          env: staging
      Events:
        Hello:
          Type: Api
          Properties:
            Path: /checkLogPresence/{time}/{delta}
            Method: GET
  GetLogMessagesFunction:
    Type: AWS::Serverless::Function
    package:
      individually: true
      exclude:
        - aws-java-sdk
    Properties:
      FunctionName: GetLogMessages
      Description: Function to check the presence of the log given a timestamp and return MD5 log message
      Runtime: java8
      Handler: proxy.ApiGatewayProxyHandler
      CodeUri: target/scala-3.0.2/acappe2_hw3.jar
      MemorySize: 512
      Timeout: 50
      Environment:
        Variables:
          env: staging
      Events:
        Hello:
          Type: Api
          Properties:
            Path: /getLogMessages/{time}/{delta}
            Method: GET
  GetLogMessagesPostFunction:
    Type: AWS::Serverless::Function
    package:
      individually: true
      exclude:
        - aws-java-sdk
    Properties:
      FunctionName: GetLogMessagesPost
      Description: Function to check the presence of the log given a timestamp and return MD5 log message with POST method
      Runtime: java8
      Handler: proxy.ApiGatewayProxyHandler
      CodeUri: target/scala-3.0.2/acappe2_hw3.jar
      MemorySize: 512
      Timeout: 50
      Environment:
        Variables:
          env: staging
      Events:
        Hello:
          Type: Api
          Properties:
            Path: /getLogMessages
            Method: POST
  CheckLogPresencePostFunction:
    Type: AWS::Serverless::Function
    package:
      individually: true
      exclude:
        - aws-java-sdk
    Properties:
      FunctionName: CheckLogPresencePost
      Description: Function to check the presence of the log given a timestamp with POST method
      Runtime: java8
      Handler: proxy.ApiGatewayProxyHandler
      CodeUri: target/scala-3.0.2/acappe2_hw3.jar
      MemorySize: 512
      Timeout: 50
      Environment:
        Variables:
          env: staging
      Events:
        Hello:
          Type: Api
          Properties:
            Path: /checkLogPresence
            Method: POST

Outputs:
  ApiURL:
    Description: "API endpoint production environment URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/checkLogPresence/15:55:27.596/10"
